#!/bin/sh
# Make sure all local dependencies are avaialable.
# requires a stable mango connection

set -e

cd $(dirname "$0")/..

VENV=.venv

# get jydoop
git submodule update --init --recursive

cd jydoop
make download
cd ../

if [ ! -d "$VENV/bin" ]; then
  virtualenv $VENV --no-site-packages
fi

source $VENV/bin/activate
pip install -q -r requirements/compiled.txt
pip install -q -r requirements/prod.txt


make clean
make download

# package up jydoop
if [ -f jydoop/scripts/dashboard.py ]; then
    rm jydoop/scripts/dashboard.py
fi
cp dashboard.py jydoop/scripts

if [ -f jydoop/scripts/histogram_specs.json ]; then
    rm jydoop/scripts/histogram_specs.json
fi
cp histogram_specs.json jydoop/scripts

# Copy everything to mango, hop over and run the job, copy the result back
ssh mango << EOT
rm -rf jydoop/
exit
EOT

scp -r jydoop mango:
ssh mango << EOT
cd jydoop/
time make ARGS="scripts/dashboard.py out.txt 20130429-yyyyMMdd 20130429-yyyyMMdd" hadoop
exit
EOT
scp mango:jydoop/out.txt .

if [ -d html/data ]; then
    rm -rf html/data
fi
python mr2disk.py html/data < out.txt
