#!/bin/sh
# Make sure all local dependencies are avaialable.
# requires a stable mango connection

set -e

cd $(dirname "$0")/..

# get jydoop
git submodule update --init --recursive

pushd jydoop
make download
popd

# TODO: need a better virtual env solution
# compiled libs will magically be there in prod

make clean
make download

# package up jydoop
if [ -f jydoop/scripts/dashboard.py ]; then
    rm jydoop/scripts/dashboard.py
fi
cp dashboard.py jydoop/scripts

if [ -f jydoop/scripts/histogram_specs.json ]; then
    rm jydoop/scripts/histogram_specs.json
fi
cp histogram_specs.json jydoop/scripts

# Copy everything to mango, hop over and run the job, copy the result back
ssh mango << EOT
rm -rf jydoop/
exit
EOT

scp -r jydoop mango:
ssh mango << EOT
cd jydoop/
time make ARGS="scripts/dashboard.py out.txt 20130731-yyyyMMdd 20130731-yyyyMMdd" hadoop
exit
EOT
scp mango:jydoop/out.txt .

if [ -d html/data ]; then
    rm -rf html/data/*
fi

python mr2disk.py html/data < out.txt

rm out.txt
#shutitdown
